In [1]:
import numpy as np

In [92]:
class srg(object):
    def __init__(self):
        self.reg = [1,0,1,1,1,0,1,1]  # the "initial fill" a.k.a.  "seed"
        self.taps = [1,2,5,7]  # a maximal length sequence generator
        #self.taps = [2,6]     # a non-maximal length generator
        
    def __repr__(self):
        n = str(self.reg) + '\n' + str(self.numrep())
        return n
    
    def numrep(self):
        self.numval = int("".join([str(int(xx)) for xx in s.reg]),base=2)
        return str(self.numval)
    
    def cycle(self):
        tapbits = [self.reg[xx] for xx in self.taps]
        #newbit = np.logical_xor(*[np.array([xx]) for xx in tapbits]).flatten()
        newbit = sum(tapbits)%2
        self.reg = [newbit] + self.reg[:-1]
        #print(self.reg, '\n',self.numrep())
        self.numrep()
        return self.numval


In [97]:
s = srg()

In [98]:
print(np.matrix([s.cycle() for xx in range(2**8+16)]).reshape(16,17))

[[ 93 174  87 171  85 170 213 234 117  58 157  78  39 147 201 100 178]
 [217 108 182  91  45 150 203 101  50 153 204 102 179  89  44  22 139]
 [197 226 113 184 220 110 183 219 109  54  27 141  70  35  17 136  68]
 [ 34 145 200 228 242 121 188  94  47 151  75  37 146  73  36  18   9]
 [132 194 225 240 120  60  30 143  71 163  81  40 148 202 229 114  57]
 [ 28 142 199 227 241 248 124 190  95 175 215 235 245 122  61 158 207]
 [231 115 185  92  46  23  11 133  66 161  80 168 212 106  53 154  77]
 [166  83  41  20 138  69 162 209 104  52  26  13   6 131 193  96  48]
 [152  76  38  19 137 196  98  49  24  12 134 195  97 176 216 236 246]
 [251 253 126 191 223 239 119  59  29  14 135  67  33  16   8   4 130]
 [ 65  32 144  72 164  82 169  84  42 149  74 165 210 233 244 250 125]
 [ 62  31  15   7   3 129 192 224 112  56 156 206 103  51  25 140 198]
 [ 99 177  88 172  86  43  21  10   5   2   1 128  64 160 208 232 116]
 [186 221 238 247 123 189 222 111  55 155 205 230 243 249 252 254 255]
 [127 

In [95]:
s

[1, 0, 1, 1, 0, 0, 1, 0]
178

In [24]:
int("".join([str(int(xx)) for xx in [True, False, True, True, True, True, False, False]]), base=2)

188

In [23]:
4+8+16+32+128


188